language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: RsJ4se7c0AKLnmEODUTCo1YqWwy1iAQl4FiMCfo+xEiKUJdJUNC+BFYKFpa87p7uyUgTgPUlHbLebjsW3vAsBBW5EIhza3OTvv0hSpgRfCM/y6mv7EOodYkLXTZMcDf5Qvjrn3hbAsfzMKxi2NWf2IT1c2h7kDT7caujLSdb9fCuBtJK1syTqaYOVsZuDLKJ2ZBORVkOvoNXuXegBusRBlS+N4iC/024iYhu4Flva0dbVrTdp/oZf448xawp1S+ldXrL9Q3Ape4DXozsIhVab6diG6kTc/cpfykdU+oGWIwwXdpKb0zQ6BOGtEh2qfkxaaqJte72IQ00ytwXrwTaDeP4OH34gYx8Q9tWdpTwo+G681Hy3ucSFEs+7CT7bBq9Jm1DJs306KCg1B0IXVSCrOM0f724Et+hYF3LnADIlS/33MVqxgB+0pzJWHMOvEkbRG4ZqF6H+w4T9hIF1CU7peT7Rje3qCLNmzo2M4xw0T3uAjqyr9hoGH1XpSvPiCuehzyVFPh5fYJvkT/A21n5m2E374rdg7QPHW8dyc1ksh0zj7q4lzMYeeEv0K6FxU+nPjXlrBL7GUerPHi0krp5nD5aHKQ2IkjM4tE0Zi6FvP4Olp7f2hKVl12XlMx+NKSI4JwsJMFTO3mf0bSxLUI300Aux5FA4lJimXYt+ZpA9PU=
