language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: dOJCqpL/D/sgpOJ440gNc5F/C+UGY93vYKXzJCdLk+J9Fyooh62AEvgcyWn7CRW9rplBh5GMTy3mDEZIp5xxxZ/+HGIPDAQfiZZ/S/RT2X/iFOyeCXj1DHTqPAc0SJvsJMlx8btUrZMmHtSVRI+FQn/Tt8OTMgRpIGeNTh4gd//uU6FEyZ9UTF44uElR4etnSsXB9Zq8i6Pa0hVJ5fNAhlsaplMfRAFHR0rFuFjs/gHPnvaJZbV4yrUNgQf3LFZkUSACIIjjMB283o6U240u8JXHYvzJJWghKcnQMKKQjaXAnQ6SyA+nUlbaMZ4Jd3V1mzi6xGfE5bTmYNFHytWLxuGW8HNRuIWHVZheK9EMkaQ38yCcHxWt7hYDUr7tFcKnFPCI0pLbtqXvt6VWkY26HRxO45LvFNdzgSuld4wgVIFFqDHqpCjhzJJ7DXNO7fb5Gp1Ulp4NOJXIe8hwoqnJnG9Mjo9Mfme5BdLXQwHlEk8OWqGxFu9UxrLYDMYIRpGeY+OfDTdSsfGvadTwkWWHIz40AY30VwN6KTlImCd0uMxNrUq4K/g3z+v4gsVqBPo8GX1djB511v8hAY7F7O42D0ZXKcigw6+APyA2Yq11YmQ4NMgUuyFlDTHjtaqD4e+vIpU1zYH1QN+dEDIzJpStoE/GtZb8cyGcyf2ArC4sdO4=
