language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: x7qbSCWfgTq2BsZkVosqXeX/z3I0ZcB81EmYZ5IM8hxttzCv/+XkkTjNXFjZ7oexUWKisEpAmjhOgEoEHRGLoFesdk+BrZTv4N4eF7d5Nr32cq8SJi6QGM08N4qNxWQ9Xt+SrLXy7HhcSFuDlv18fQj7hVoN6TwLoFe4//TbKKmCmnN7GoazcJ/MvCdPX9guU+2G23BaCMICiIRwYAO53//wPDNO7mGJmVFvz4tEa/7mZuH5f+yzFOfMX0XSqJbOGBUEoBsnEtNShy/4hRHf+NU5lJiadG+HQmbNipJnIw1ILmJX/JF7YXNQmlQXiAl8Vm8gd7z8IiMfzmMlbXeAGRbTUdbCwkoLj8k44Ho7fUtjT/SY/7NZjyrA7PVVCOdc7ZVWYrZ3A1c65gEnGuZfACKugIbIfMdkEdTM7tRi1vT+Id3b80O68TRXUbM2qLlPUqSGNXDB7Mm9Z4UKItu0ESpjPrW5CglJty+fmL5HL8AyS21gTF5rbmsylfBdZ2P0l+SH0hIzW8O0j+wKPEYayxxDribqQ2RwRK72R5l/MrUelk0I8qqH9c4blYK9+kYTU/PyfK4W47R5kWgRLKgitknzLtWotBRL31CusfEjIb++CvtVRKuYUgKYbP0VRNSl52mUHg8yVNLhTmwsBWN7bEe/GhCNFAXpemHpnXY1ccE=
  app: rohan-the-egg
  on:
    repo: rohanpritchard/BasicWebApp
