language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: CRRccs+BmlmD3xWUTKTk8X7bokgqe41Y3EEQ6cAd7qmoNH0uEu9a/sOknXRJDMWqEI4UBd5eUmyPEEUhHCCvNoNpa1BD8c7mZNC1tMbufaDmTxrpqDLS8n2095WsaQwCEkyLcxp9a+OMnR7IMrzaN5x5utQFVoFtNGTnMWkqZeaYFDtC9L/gRMJyqePm/i1LGTNpJJRRIEkvMfFRHZM5D7pACc9BJ5gFBXoW8NF1Os8EMGHC2GOYhT+orP6kls6jnpn8VCciNbGCJQIq5pVsvqYSc0OmoeutOwYC0aTstt668uzCCSA0kxm7OgRl7dljeoPWYeFm5EjEYsPG8nyi+34Ae1L5m5PPgfjebSktc0ulyJ7SEaGXAJ5V95yK4GjTp2RCYbFeO4jOZmPZPfbdba+t4SKic8bQNMNXCu61v8cfhwd6CCtppO7V+Arh6rbcvWPvhW56PyvEU6mHNQ0/6hKqD5bjqPjdTmKSFSi4ELU4QSTyxgrWglKIneaAY5nJeN+B8eLeuBy74bac7OGTev8f1Pr1v948RAhQLwYk/iiJgHPojJGNBpjmaeVtcDrWFBY/Zaa0Y3nkU2ExEtAPZxbqvSWvX9opPScyKn6KDOnbkbkw5992lUqmMWtQ5rXM/GwzbWbOvDfYenLMUwZw85cVeRtPaCAdpLfOYai7cnk=
  app: rohan-the-egg
  on:
    repo: rohanpritchard/BasicWebApp
