language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: fw+yUgT/LmP+YzpBmljZgZ22jAAyQGAxuAjUiAzaLT9vm4nwCS4Hf4UsOGY6oT9N+Lc98uCI7C5iHgKrwMreDGbol781/U3hhBEAqQWY4noDxRmhmDtavVV3W2c9MOG8KwhGOP4Bb+6qaSWsbzDxSYSKs4YHoZsVi/KTsTw/LQ47XcO/GM9Nvpc4CuXXuwucUpgi4TlK3dvoGb/Y9R1k/U4b487tJfPPpdHLvk+o1XnHVh+zH0ME8izTA+86GJ9ICm/iYLuN80SYmlfSE9fDLKjEQ30ITLKOgXu8q6MCqRdfIcW/CeNbPgo0vW9CA3weWiUEKDBnSMEmdTWkGuaWUuo+HfLvordhVM1Jjo7z6kfj+bm0jl4CePJ6dwsk68Mdx1xc0qFoFkn1bj044AaUZSx7fmuTyAbcrolKn/hsy1nFY5rOhxlRCh9LVsDawmcRRUfjOfaS2UWnMnCw3i15dYV3nsPMW9ca0+Oa/dE7LcAroKSXbOKb3tLQCMVZHJrCcWEP74kMjoBaDJIcoDGgtRzMwdD7B1hf4yOP5VVcveF2WdZO8ts6WNJoAYFgcEG5lkw9ubGALVl+qaoNmNDtSR0HCwYwj8fMdBLBpD3MzvhxnA90o19N71O3Eld63THbQvXB8W6SHFE6PSmeUM8fiLm5jeid4BeCQbnILB5sXyw=
  app: rohan-the-egg
  on:
    repo: rohanpritchard/BasicWebApp
